---
# Setup Jenkins on a Fedora system.

- name: update repo
  ansible.builtin.get_url:
    url: "{{ rpm_repo }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ rpm_key }}"

- name: dnf update
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: install software
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
      - jenkins
      - git
      - docker
    state: latest

- name: reload systemd config
  ansible.builtin.systemd:
    daemon_reload: true

- name: start systemd jenkins
  ansible.builtin.systemd:
    name: jenkins.service
    state: started
    enabled: true

- name: start systemd docker
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true

- name: Allow httpd in firewalld
  firewalld:
    port: "8080/tcp"
    permanent: true
    state: enabled
  when: ansible_distribution == "Fedora"
  notify: firewalld reload

- name: create jenkins user
  user:
    name: "{{ jenkins_name }}"
    append: true
    groups: ["docker"]
    system: true

- name: create admin user
  tags: user,admin-user
  user:
    name: "{{ admin_name }}"
    password: "{{ admin_passwd }}"
    append: true
    groups: ["wheel"]

- name: add ssh key for admin
  tags: user
  authorized_key:
    user: "{{ admin_name }}"
    key: "{{ ssh_public_key }}"

- name: add admin to sudoers
  tags: user
  community.general.sudoers:
    name: admin-user
    user: "{{ admin_name }}"
    commands: ALL
    nopassword: false

- name: disable root ssh
  tags: ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'

- name: disable passwd ssh
  tags: ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

- name: restart systemd sshd
  tags: ssh
  ansible.builtin.systemd:
    name: sshd.service
    state: restarted
